from pathlib import Path

MINI_IP_HTML = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mini IP</title>
<style>
body{margin:0;background:#08090d;color:#f5f6fa;font:15px system-ui;padding:18px}main{max-width:1100px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.brand{font-size:28px;font-weight:900}.muted{color:#9299a8}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.card{background:#11141b;border:1px solid #292f3c;border-radius:16px;padding:17px}.wide{grid-column:1/-1}h2{font-size:17px;margin:0 0 12px}.pill{padding:7px 11px;border:1px solid #29303d;border-radius:999px}.ok{color:#67e3a1}.bad{color:#ff667e}input,textarea{width:100%;box-sizing:border-box;background:#090c12;color:white;border:1px solid #303746;border-radius:10px;padding:10px;font:inherit}textarea{min-height:90px}.label{font-size:12px;color:#9299a8;margin:9px 0 5px}button{margin:8px 6px 0 0;padding:10px 13px;border-radius:10px;border:1px solid #303746;background:#191e28;color:white;font-weight:700;cursor:pointer}button.primary{background:#8756ed;border:0}.kv{display:grid;grid-template-columns:150px 1fr;gap:5px 10px;font-size:13px}pre{white-space:pre-wrap;word-break:break-word;background:#090c11;padding:12px;border-radius:10px}.gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:10px}.tile{background:#090c11;border:1px solid #292f3c;border-radius:10px;overflow:hidden}.tile img{width:100%;aspect-ratio:1;object-fit:cover}.tile div{padding:7px;font-size:11px;color:#9299a8}@media(max-width:720px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body><main>
<div class="top"><div><div class="brand">MINI IP</div><div class="muted">Character → Image Content → Social → Audience → Learning → Character Evolution</div></div><div id="server" class="pill">CONNECTING…</div></div>
<div class="grid">
<section class="card"><h2>1 · Character</h2><div class="label">Имя</div><input id="name" value="Леся"><div class="label">MASTER DNA / влияние владельца</div><textarea id="dna" placeholder="Характер, стиль, голос, поведение, визуальные особенности…"></textarea><button class="primary" onclick="saveCharacter()">Сохранить</button><button onclick="randomDNA()">Случайная ДНК</button></section>
<section class="card"><h2>2 · Image Content Factory</h2><div class="label">Brief</div><textarea id="brief">Кафе в Москве. Леся с капучино смотрит прямо в камеру. Ложкой размешивает кофе по часовой стрелке и говорит: «Тоже в эту сторону».</textarea><button class="primary" onclick="produce()">Создать контент</button><button onclick="refresh()">Обновить</button><pre id="result">Фабрика готова.</pre></section>
<section class="card wide"><h2>3 · Character Card</h2><div class="kv"><span>Владелец</span><b id="owner">—</b><span>Персонаж</span><b id="profileName">—</b><span>Артефактов</span><b id="count">0</b><span>Последний сигнал</span><b id="signal">—</b><span>Эволюция</span><b id="evolution">—</b></div></section>
<section class="card wide"><h2>4 · Content Gallery</h2><div id="gallery" class="gallery"><span class="muted">Пока пусто.</span></div></section>
<section class="card"><h2>5 · Learning / Signals</h2><p class="muted">Результаты циклов сохраняются и становятся входом для следующего решения.</p><button onclick="refresh()">Синхронизировать</button></section>
<section class="card"><h2>6 · Evolution</h2><p class="muted">После проверенного результата следующий цикл может развивать Character DNA.</p><button class="primary" onclick="produce()">Следующий цикл</button></section>
<section class="card wide"><details><summary>Техническое состояние</summary><pre id="debug">—</pre></details></section>
</div></main>
<script>
let owner=localStorage.mini_ip_owner||'',character=localStorage.mini_ip_character||'',token=localStorage.mini_ip_token||'';
const $=id=>document.getElementById(id);
function headers(){let h={'Content-Type':'application/json','X-Owner-ID':owner};if(token)h.Authorization='Bearer '+token;return h}
async function api(p,o={}){o.headers=Object.assign(headers(),o.headers||{});let r=await fetch(p,o),x=await r.json().catch(()=>({}));if(r.status===401)throw Error('Требуется токен доступа');if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));return x}
async function auth(){try{let c=await fetch('/config').then(r=>r.json());if(c.auth_required&&!token){token=prompt('Введите токен доступа Mini IP:')||'';localStorage.mini_ip_token=token}if(!owner){let x=await api('/owners',{method:'POST',body:'{}'});owner=x.owner_id;localStorage.mini_ip_owner=owner}await refresh()}catch(e){$('server').textContent='AUTH / ERROR';$('server').className='pill bad';$('debug').textContent=e.message}}
async function ensureCharacter(){if(character)return character;let x=await api('/characters',{method:'POST',body:JSON.stringify({owner_id:owner,name:'Леся',card:{description:'Adult fictional character; copper-red strict bob with straight fringe; expressive greenish eyes; direct eye contact; Moscow visual language; natural asymmetry 10–15%.',user_controls:{dna_notes:'',voice:{source:'synthetic'}}}})});character=x.character_id;localStorage.mini_ip_character=character;return character}
async function saveCharacter(){try{await ensureCharacter();let x=await api('/characters/'+character+'/preferences',{method:'POST',body:JSON.stringify({owner_id:owner,patch:{dna_notes:$('dna').value,voice:{source:'synthetic',description:'Character voice DNA'}}})});$('result').textContent='Character saved · version '+x.version;await refresh()}catch(e){$('result').textContent=e.message}}
async function randomDNA(){try{await ensureCharacter();let x=await api('/characters/'+character+'/randomize-dna',{method:'POST',body:JSON.stringify({owner_id:owner})});let d=(x.card||{}).user_controls?.random_dna||{};$('dna').value=Object.entries(d).map(([k,v])=>k+': '+v).join(', ')}catch(e){$('result').textContent=e.message}}
async function produce(){try{await saveCharacter();let x=await api('/jobs',{method:'POST',body:JSON.stringify({owner_id:owner,character_id:character,platform:'local-test'})});$('result').textContent='QUEUED · '+x.job_id;let id=x.job_id,n=0,t=setInterval(async()=>{try{let j=await api('/jobs/'+id);$('result').textContent=JSON.stringify(j,null,2);if(['SUCCEEDED','DEAD_LETTER','FAILED'].includes(j.status)||++n>120){clearInterval(t);refresh()}}catch(e){clearInterval(t);$('result').textContent=e.message}},1500)}catch(e){$('result').textContent=e.message}}
async function refresh(){try{let h=await fetch('/health').then(r=>r.json()),rr=await fetch('/ready'),rd=await rr.json();$('server').textContent=rr.ok?'ONLINE':'NOT READY';$('server').className='pill '+(rr.ok?'ok':'bad');if(!owner)return;let s=await api('/status/'+owner),c=(s.characters_detail||[]).find(x=>x.character_id===character)||(s.characters_detail||[])[0];if(c&&!character){character=c.character_id;localStorage.mini_ip_character=character}if(c){$('profileName').textContent=c.name;$('name').value=c.name;$('dna').value=(c.card?.user_controls?.dna_notes)||$('dna').value}let jobs=s.jobs_detail||[],active=jobs.find(j=>['QUEUED','RUNNING'].includes(j.status));$('owner').textContent=owner.slice(0,18)+'…';$('count').textContent=(s.artifacts_detail||[]).length;$('signal').textContent=jobs[0]?.status||'—';$('evolution').textContent=active?'Ожидает завершения':'Готова';$('debug').textContent=JSON.stringify({health:h,ready:rd,owner,character,jobs:jobs.slice(0,8)},null,2);await gallery(s.artifacts_detail||[])}catch(e){$('debug').textContent=e.message}}
async function gallery(items){if(!items.length){$('gallery').innerHTML='<span class="muted">Пока нет готовых артефактов.</span>';return}$('gallery').innerHTML='';for(const a of items.slice().reverse()){let d=document.createElement('div');d.className='tile';let img=document.createElement('img');try{let r=await fetch('/artifacts/'+a.artifact_id,{headers:headers()});img.src=URL.createObjectURL(await r.blob())}catch(e){}d.appendChild(img);let m=document.createElement('div');m.textContent=(a.variant||'artifact')+' · '+(a.status||'');d.appendChild(m);$('gallery').appendChild(d)}}
auth();setInterval(refresh,10000);
</script></body></html>"""

def send_mini_ip(self):
    body = MINI_IP_HTML.encode("utf-8")
    self.send_response(200)
    self.send_header("Content-Type","text/html; charset=utf-8")
    self.send_header("Cache-Control","no-store, no-cache, must-revalidate, max-age=0")
    self.send_header("Content-Length",str(len(body)))
    self.end_headers()
    self.wfile.write(body)
