from pathlib import Path

MINI_IP_HTML = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mini IP</title>
<style>
:root{--bg:#f6f7f9;--card:#fff;--text:#17191f;--muted:#707784;--line:#e5e7eb;--accent:#6d45e8;--soft:#f0ebff;--ok:#14804a;--bad:#c92f4b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:760px;margin:auto;padding:16px 14px 48px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.brand{font-size:22px;font-weight:900;letter-spacing:-.03em}.muted{color:var(--muted)}.pill{padding:6px 9px;border:1px solid var(--line);border-radius:999px;background:#fff;font-size:12px}.ok{color:var(--ok)}.bad{color:var(--bad)}
.hero{padding:24px 20px;background:var(--text);color:#fff;border-radius:24px;margin-bottom:12px}.hero .eyebrow{font-size:11px;letter-spacing:.12em;font-weight:800;opacity:.65}.hero h1{font-size:31px;line-height:1.08;letter-spacing:-.04em;margin:8px 0}.hero p{color:#c8cbd2;line-height:1.5;margin:0;max-width:620px}.hero-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:20px}
.card{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:18px;margin-bottom:12px}.card h2{font-size:18px;margin:0 0 5px;letter-spacing:-.02em}.step{font-size:11px;font-weight:800;color:var(--accent);text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px}.wide{width:100%}
button{border:1px solid var(--line);background:#fff;color:var(--text);font:inherit;font-weight:700;padding:12px 14px;border-radius:12px;cursor:pointer}button.primary{background:var(--accent);border-color:var(--accent);color:#fff}button.big{padding:13px 14px}button.selected{border-color:var(--accent);background:var(--soft);box-shadow:0 0 0 2px rgba(109,69,232,.12)}
.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.choice-grid button{text-align:left;min-height:58px}.choice-grid small{display:block;color:var(--muted);font-weight:500;margin-top:3px}
textarea,input{width:100%;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--text);font:inherit;padding:12px;margin-top:6px}textarea{min-height:92px;resize:vertical}.label{font-size:12px;color:var(--muted);margin-top:13px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}
.growth-status{margin-top:12px;padding:12px;border-radius:12px;background:#f7f7f9;color:var(--muted);line-height:1.45}.photo-preview{margin-top:10px}.photo-preview img{width:100%;max-height:320px;object-fit:contain;border-radius:14px;background:#f2f3f5}.upload{border:1.5px dashed #cdd1da;border-radius:14px;padding:18px;text-align:center;margin-top:10px}.upload input{border:0;padding:0;margin:0}.result{padding:12px;background:#f7f7f9;border-radius:12px;min-height:20px;line-height:1.45}
.summary{display:grid;grid-template-columns:1fr 1fr;gap:8px}.summary div{background:#f7f7f9;padding:12px;border-radius:12px}.summary span{display:block;color:var(--muted);font-size:12px;margin-bottom:3px}
.gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.tile{background:#f7f7f9;border-radius:14px;overflow:hidden}.tile img{width:100%;aspect-ratio:1;object-fit:cover}.tile div{padding:7px;font-size:11px;color:var(--muted)}
.next{position:sticky;bottom:10px;background:rgba(246,247,249,.94);padding-top:8px}.next button{width:100%;font-size:16px}
details{color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;background:#f7f7f9;padding:12px;border-radius:12px;font-size:11px}
@media(max-width:520px){main{padding:10px 10px 36px}.hero{padding:20px 16px;border-radius:20px}.hero h1{font-size:27px}.hero-actions,.choice-grid{grid-template-columns:1fr}.card{padding:15px;border-radius:17px}.summary{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><div><div class="brand">MINI IP</div><div class="muted">Студия развития персонажа</div></div><div id="server" class="pill">ПОДКЛЮЧЕНИЕ…</div></div>

<section class="hero"><span class="eyebrow">ТВОЙ ПЕРСОНАЖ</span><h1>Давай найдём его путь.</h1><p>Ты задаёшь мечту — Mini IP помогает проверить разные варианты и найти сильную сторону персонажа.</p><div class="hero-actions"><button class="primary big" onclick="showGrowth()">Выбрать направление</button><button class="big" onclick="startDiscovery()">Удиви меня</button></div></section>

<section class="card" id="growth-card"><div class="step">Шаг 1 · Направление</div><h2>Кем ты хочешь его видеть?</h2><p class="muted">Можно выбрать несколько или вообще ничего не выбирать.</p>
<div id="growth-options" class="choice-grid">
<button onclick="chooseGrowth('Популярность')">🌟 Популярным<small>Чтобы его узнавали</small></button>
<button onclick="chooseGrowth('История и личность')">📖 Сильной личностью<small>Характер и собственная история</small></button>
<button onclick="chooseGrowth('Медиа')">🎬 Медийным<small>Истории, шоу и контент</small></button>
<button onclick="chooseGrowth('Визуальный IP')">🎨 Визуальным IP<small>Образ и узнаваемый стиль</small></button>
<button onclick="chooseGrowth('Социальные сети')">📱 Персонажем соцсетей<small>Аудитория и общение</small></button>
<button onclick="chooseGrowth('Коммерческий IP')">💼 Коммерческим IP<small>Бренды и будущая монетизация</small></button>
<button onclick="chooseGrowth('Голос и выступления')">🎤 Голосом и выступлениями<small>Речь, музыка, сцена</small></button>
<button onclick="chooseGrowth('Эксперимент')">🧪 Пока ищем<small>Пусть система попробует варианты</small></button></div>
<div class="label">Или расскажи своими словами</div><textarea id="growth-brief" placeholder="Например: хочу, чтобы Леся стала узнаваемой, имела свой характер и со временем могла стать коммерческим персонажем."></textarea>
<div class="actions"><button class="primary" onclick="saveGrowth()">Сохранить мой замысел</button><button onclick="startDiscovery()">Пусть Mini IP найдёт путь</button></div>
<div id="growth-status" class="growth-status">Пока направление не выбрано.</div></section>

<section class="card"><div class="step">Шаг 2 · Персонаж</div><h2>Создай основу</h2><div class="label">Имя</div><input id="name" value="Леся"><div class="label">Что в нём важно</div><textarea id="dna" placeholder="Характер, стиль, поведение, внешность…"></textarea><div class="actions"><button class="primary" onclick="saveCharacter()">Сохранить персонажа</button><button onclick="randomDNA()">Создать случайный вариант</button></div></section>

<section class="card"><div class="step">Шаг 3 · Внешность</div><h2>Фотография персонажа</h2><p class="muted">Необязательно. Это визуальный референс — он помогает сохранять узнаваемость.</p><div class="upload"><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onchange="previewPhoto()"></div><div id="photo-preview" class="photo-preview" style="display:none"><img id="photo-img"></div><div class="actions"><button class="primary" onclick="uploadPhoto()">Сохранить фотографию</button></div><div id="photo-status" class="growth-status">Фотография ещё не добавлена.</div></section>

<section class="card"><div class="step">Шаг 4 · Первый контент</div><h2>Что сейчас происходит?</h2><textarea id="brief">Кафе в Москве. Леся с капучино смотрит прямо в камеру. Ложкой размешивает кофе по часовой стрелке и говорит: «Тоже в эту сторону».</textarea><div class="next"><button class="primary" onclick="produce()">Создать первый контент</button></div><div id="result" class="result" style="margin-top:10px">Фабрика готова.</div></section>

<section class="card"><div class="step">Твой персонаж</div><h2 id="profileName">Леся</h2><div class="summary"><div><span>Материалов</span><b id="count">0</b></div><div><span>Последний результат</span><b id="signal">—</b></div><div><span>Развитие</span><b id="evolution">Готово</b></div><div><span>Владелец</span><b id="owner">—</b></div></div></section>

<section class="card"><div class="step">Библиотека</div><h2>Твои результаты</h2><div id="gallery" class="gallery"><span class="muted">Пока пусто.</span></div></section>

<section class="card"><details><summary>Техническое состояние</summary><pre id="debug">—</pre></details></section>
</main></body><script>
let owner=localStorage.mini_ip_owner||'',character=localStorage.mini_ip_character||'',token=localStorage.mini_ip_token||'';
let growth=JSON.parse(localStorage.mini_ip_growth||'null')||{direction:'',directions:[],brief:'',mode:'',discovery:false,jobs:[]};
if(!Array.isArray(growth.directions))growth.directions=growth.direction?[growth.direction]:[];
function syncGrowthDirections(){growth.direction=growth.directions.join(' + ')}
function persistGrowth(){localStorage.mini_ip_growth=JSON.stringify(growth)}
function showGrowth(){document.getElementById('growth-card')?.scrollIntoView({behavior:'smooth',block:'start'})}
function chooseGrowth(direction){const i=growth.directions.indexOf(direction);if(i>=0)growth.directions.splice(i,1);else growth.directions.push(direction);syncGrowthDirections();document.querySelectorAll('#growth-options button').forEach(b=>b.classList.toggle('selected',growth.directions.some(d=>b.textContent.includes(d))));$('growth-status').textContent=growth.directions.length?'Выбрано: '+growth.directions.join(', ')+'. Можно добавить свой замысел или сразу начать поиск.':'Пока направление не выбрано.';persistGrowth()}
async function saveGrowth(){try{await ensureCharacter();growth.brief=$('growth-brief').value.trim();growth.mode='owner-guided';if(!growth.direction)growth.direction='Свободное развитие';persistGrowth();await api('/characters/'+character+'/preferences',{method:'POST',body:JSON.stringify({owner_id:owner,patch:{growth_plan:{direction:growth.direction,brief:growth.brief,mode:growth.mode}}})});$('growth-status').innerHTML='<span class="ok">✓ Замысел сохранён.</span> Mini IP будет использовать его как ориентир, но направление можно изменить в любой момент.'}catch(e){$('growth-status').textContent=e.message}}
async function startDiscovery(){try{await ensureCharacter();growth.discovery=true;growth.mode='discovery';growth.jobs=[];persistGrowth();$('growth-status').textContent='Mini IP запускает небольшую обкатку: проверяем несколько разных сторон персонажа…';const ideas=[['Повседневность','discovery_daily','Персонаж в простой узнаваемой жизненной ситуации'],['Юмор','discovery_humor','Короткая ироничная ситуация, раскрывающая характер'],['История','discovery_story','Небольшая эмоциональная история персонажа'],['Визуальный образ','discovery_visual','Сильная визуальная сцена для проверки узнаваемости'],['Общение','discovery_social','Ситуация, рассчитанная на реакцию аудитории'],['Неожиданность','discovery_surprise','Необычная ситуация, способная выделить персонажа']];for(const idea of ideas){const context=(growth.direction?'Ориентиры развития: '+growth.direction+'. ':'')+(growth.brief?'Замысел владельца: '+growth.brief+'. ':'');const brief=context+idea[2];const x=await api('/jobs',{method:'POST',body:JSON.stringify({owner_id:owner,character_id:character,platform:'local-test',brief,idea:{mechanic:idea[1],hook:idea[2],brief:brief}})});growth.jobs.push({id:x.job_id,label:idea[0],mechanic:idea[1]})}persistGrowth();$('growth-status').textContent='✓ Обкатка запущена. Mini IP проверяет 6 разных вариантов и будет использовать результаты для следующего решения.';pollDiscovery()}catch(e){$('growth-status').textContent=e.message}}
async function pollDiscovery(){if(!growth.jobs?.length)return;let done=0;for(const j of growth.jobs){try{const x=await api('/jobs/'+j.id);j.status=x.status;if(['SUCCEEDED','DEAD_LETTER','FAILED'].includes(x.status))done++}catch(e){}}persistGrowth();$('growth-status').textContent=done===growth.jobs.length?'✓ Обкатка завершена. Mini IP собрал первый опыт персонажа.':'Идёт обкатка персонажа: '+done+'/'+growth.jobs.length+' экспериментов завершено.';if(done<growth.jobs.length)setTimeout(pollDiscovery,1800);else refresh()}
const $=id=>document.getElementById(id);
function headers(){let h={'Content-Type':'application/json','X-Owner-ID':owner};if(token)h.Authorization='Bearer '+token;return h}
async function api(p,o={}){o.headers=Object.assign(headers(),o.headers||{});let r=await fetch(p,o),x=await r.json().catch(()=>({}));if(r.status===401)throw Error('Требуется ключ доступа');if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));return x}
async function auth(){try{let c=await fetch('/config').then(r=>r.json());if(c.auth_required&&!token){token=prompt('Введите токен доступа Mini IP:')||'';localStorage.mini_ip_token=token}if(!owner){let x=await api('/owners',{method:'POST',body:'{}'});owner=x.owner_id;localStorage.mini_ip_owner=owner}await refresh()}catch(e){$('server').textContent='ОШИБКА ДОСТУПА';$('server').className='pill bad';$('debug').textContent=e.message}}
async function ensureCharacter(){if(character)return character;let x=await api('/characters',{method:'POST',body:JSON.stringify({owner_id:owner,name:'Леся',card:{description:'Взрослый вымышленный персонаж; строгий медно-рыжий боб с прямой чёлкой; выразительные зелёно-серые глаза; прямой взгляд; московская визуальная среда; естественная асимметрия 10–15%.',user_controls:{dna_notes:'',voice:{source:'synthetic'}}}})});character=x.character_id;localStorage.mini_ip_character=character;return character}
async function saveCharacter(){try{await ensureCharacter();let x=await api('/characters/'+character+'/preferences',{method:'POST',body:JSON.stringify({owner_id:owner,patch:{dna_notes:$('dna').value,voice:{source:'synthetic',description:'Голосовая ДНК персонажа'}}})});$('result').textContent='Персонаж сохранён · версия '+x.version;await refresh()}catch(e){$('result').textContent=e.message}}
function previewPhoto(){const f=$('photo').files[0];if(!f)return;$('photo-img').src=URL.createObjectURL(f);$('photo-preview').style.display='block';$('photo-status').textContent='Фотография выбрана. Нажмите «Сохранить фотографию».'}
function clearPhoto(){$('photo').value='';$('photo-preview').style.display='none';$('photo-status').textContent='Фотография ещё не добавлена.'}
async function uploadPhoto(){try{await ensureCharacter();const f=$('photo').files[0];if(!f)throw Error('Сначала выберите фотографию');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Поддерживаются JPG, PNG и WebP');if(f.size>10*1024*1024)throw Error('Фотография должна быть не больше 10 МБ');let h={'Content-Type':f.type,'X-Owner-ID':owner,'X-Filename':f.name};if(token)h.Authorization='Bearer '+token;let r=await fetch('/characters/'+character+'/reference',{method:'POST',headers:h,body:f}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));$('photo-status').textContent='✓ Фотография сохранена и подключена к персонажу';$('photo-status').className='ok';await refresh()}catch(e){$('photo-status').textContent=e.message;$('photo-status').className='bad'}}

async function randomDNA(){try{await ensureCharacter();let x=await api('/characters/'+character+'/randomize-dna',{method:'POST',body:JSON.stringify({owner_id:owner})});let d=(x.card||{}).user_controls?.random_dna||{};$('dna').value=Object.entries(d).map(([k,v])=>k+': '+v).join(', ')}catch(e){$('result').textContent=e.message}}
async function produce(){try{await saveCharacter();let base=$('brief').value.trim(),context=(growth.direction?'Направление развития: '+growth.direction+'. ':'')+(growth.brief?'Замысел владельца: '+growth.brief+'. ':'');let fullBrief=context+base;let x=await api('/jobs',{method:'POST',body:JSON.stringify({owner_id:owner,character_id:character,platform:'local-test',brief:fullBrief,idea:{mechanic:growth.discovery?'guided_discovery':'user_brief',hook:base,brief:fullBrief,direction:growth.direction||'',owner_intent:growth.brief||''}})});$('result').textContent='В ОЧЕРЕДИ · '+x.job_id;let id=x.job_id,n=0,t=setInterval(async()=>{try{let j=await api('/jobs/'+id);$('result').textContent=({QUEUED:'В ОЧЕРЕДИ',RUNNING:'В РАБОТЕ',SUCCEEDED:'ВЫПОЛНЕНО',DEAD_LETTER:'ОСТАНОВЛЕНО',FAILED:'ОШИБКА'}[j.status]||j.status)+' · '+(j.error||'Цикл выполняется');if(['SUCCEEDED','DEAD_LETTER','FAILED'].includes(j.status)||++n>120){clearInterval(t);refresh()}}catch(e){clearInterval(t);$('result').textContent=e.message}},1500)}catch(e){$('result').textContent=e.message}}
async function refresh(){try{let h=await fetch('/health').then(r=>r.json()),rr=await fetch('/ready'),rd=await rr.json();$('server').textContent=rr.ok?'В СЕТИ':'НЕ ГОТОВ';$('server').className='pill '+(rr.ok?'ok':'bad');if(!owner)return;let s=await api('/status/'+owner),c=(s.characters_detail||[]).find(x=>x.character_id===character)||(s.characters_detail||[])[0];if(c&&!character){character=c.character_id;localStorage.mini_ip_character=character}if(c){$('profileName').textContent=c.name;$('name').value=c.name;$('dna').value=(c.card?.user_controls?.dna_notes)||$('dna').value;const gp=c.card?.user_controls?.growth_plan;if(gp&&!growth.direction){growth.direction=gp.direction||'';growth.directions=gp.direction?String(gp.direction).split(' + ').filter(Boolean):[];growth.brief=gp.brief||'';growth.mode=gp.mode||'';document.querySelectorAll('#growth-options button').forEach(b=>b.classList.toggle('selected',growth.directions.some(d=>b.textContent.includes(d))));persistGrowth()}}let gr=s.growth?.[character];if(gr?.recommendation){$('growth-status').innerHTML='<b>Mini IP видит перспективное направление:</b> '+gr.recommendation+'<br><span class="muted">Это пока гипотеза. Уверенность '+Math.round((gr.confidence||0)*100)+'%. Её нужно проверить следующими экспериментами.</span>'}else if(gr?.message&&growth.discovery){$('growth-status').textContent=gr.message} let jobs=s.jobs_detail||[],active=jobs.find(j=>['QUEUED','RUNNING'].includes(j.status));$('owner').textContent=owner.slice(0,18)+'…';$('count').textContent=(s.artifacts_detail||[]).length;$('signal').textContent=({QUEUED:'В ОЧЕРЕДИ',RUNNING:'В РАБОТЕ',SUCCEEDED:'ВЫПОЛНЕНО',DEAD_LETTER:'ОСТАНОВЛЕНО',FAILED:'ОШИБКА'}[jobs[0]?.status]||jobs[0]?.status||'—');$('evolution').textContent=active?'Идёт обучение':'Готова к следующему циклу';const ref=(s.artifacts_detail||[]).find(a=>a.character_id===character&&a.variant==='reference');if(ref){$('photo-status').textContent='✓ Фотография персонажа сохранена';$('photo-status').className='ok';} $('debug').textContent=JSON.stringify({health:h,ready:rd,owner,character,jobs:jobs.slice(0,8)},null,2);await gallery(s.artifacts_detail||[])}catch(e){$('debug').textContent=e.message}}
async function gallery(items){if(!items.length){$('gallery').innerHTML='<span class="muted">Пока нет готовых артефактов.</span>';return}$('gallery').innerHTML='';for(const a of items.slice().reverse()){let d=document.createElement('div');d.className='tile';let img=document.createElement('img');try{let r=await fetch('/artifacts/'+a.artifact_id,{headers:headers()});img.src=URL.createObjectURL(await r.blob())}catch(e){}d.appendChild(img);let m=document.createElement('div');m.textContent=({APPROVED:'ГОТОВО',PENDING:'ОЖИДАЕТ',FAILED:'ОШИБКА'}[a.status]||a.status||'')+' · '+(a.variant==='master'?'основной вариант':(a.variant||'материал'));d.appendChild(m);$('gallery').appendChild(d)}}
if(growth.direction){$('growth-status').textContent='Текущее направление: '+growth.direction+(growth.discovery?' · обкатка включена':'');if($('growth-brief'))$('growth-brief').value=growth.brief||''} auth();setInterval(refresh,10000);
</script></html>