from pathlib import Path

MINI_IP_HTML = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mini IP</title>
<style>
:root{--bg:#eef8f6;--card:#fff;--ink:#142322;--muted:#60706d;--line:#d6e6e2;--accent:#0f8f83;--accent2:#dff5f1;--ok:#087c59}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:720px;margin:auto;padding:12px 12px 90px}.top{display:flex;justify-content:space-between;align-items:center;padding:6px 2px 14px}.brand{font-weight:900;font-size:22px}.muted{color:var(--muted);line-height:1.45}.pill{font-size:12px;padding:7px 10px;border-radius:99px;background:#fff;border:1px solid var(--line)}.ok{color:var(--ok)}.bad{color:#c83250}
.hero{background:linear-gradient(135deg,#073b3a,#0f8f83 58%,#54b7a8);color:#fff;border-radius:26px;padding:24px 20px;margin-bottom:12px}.hero .eyebrow{font-size:11px;letter-spacing:.13em;opacity:.6;font-weight:800}.hero h1{font-size:32px;line-height:1.05;letter-spacing:-.04em;margin:8px 0}.hero p{margin:0;color:#c9c7cf;line-height:1.5}.hero-main{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:end;margin-top:20px}.hero-main button{min-width:170px}
.card{background:#fff;border:1px solid var(--line);box-shadow:0 6px 22px rgba(10,75,69,.06);border-radius:20px;padding:18px;margin-bottom:12px}.card h2{margin:0 0 5px;font-size:20px;letter-spacing:-.025em}.step{font-size:11px;color:var(--accent);font-weight:900;letter-spacing:.1em;text-transform:uppercase;margin-bottom:6px}
button{appearance:none;border:1px solid #dcd8e5;background:#fff;color:var(--ink);font:inherit;font-weight:750;padding:13px 15px;border-radius:13px;cursor:pointer;min-height:48px}button.primary{background:var(--accent);border-color:var(--accent);color:#fff}button.selected{background:var(--accent2);border-color:var(--accent);box-shadow:0 0 0 2px rgba(15,143,131,.16)}button:active{transform:translateY(1px)}button:disabled{opacity:.45;cursor:not-allowed}
.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.actions button{flex:1;min-width:150px}.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.choice-grid button{text-align:left}.choice-grid small{display:block;color:var(--muted);font-weight:500;margin-top:4px}
input,textarea{display:block;width:100%;font:inherit;color:var(--ink);background:#fff;border:1px solid #dcd8e5;border-radius:13px;padding:13px;margin-top:7px}textarea{min-height:92px;resize:vertical}.label{font-size:12px;color:var(--muted);margin-top:12px}
.photo-box{border:2px dashed #72bdb3;border-radius:18px;padding:20px;text-align:center;background:#effaf8;margin-top:12px}.photo-box strong{display:block;font-size:17px;margin-bottom:5px}.photo-box input{border:0;padding:0;margin:12px 0 0;background:transparent}.photo-preview{margin-top:12px}.photo-preview img{display:block;width:100%;max-height:360px;object-fit:contain;border-radius:15px;background:#f1eff5}.status{padding:12px;border-radius:12px;background:#f7f6f9;margin-top:10px;line-height:1.45}
.summary{display:grid;grid-template-columns:1fr 1fr;gap:8px}.summary div{padding:12px;background:#f7f6f9;border-radius:12px}.summary span{display:block;font-size:12px;color:var(--muted);margin-bottom:3px}.gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.tile{overflow:hidden;border-radius:14px;background:#f7f6f9}.tile img{width:100%;aspect-ratio:1;object-fit:cover}.tile div{padding:8px;font-size:11px;color:var(--muted)}
.sticky{position:sticky;bottom:10px;background:rgba(238,248,246,.96);padding-top:8px}.sticky button{width:100%;font-size:17px}details{color:var(--muted)}pre{white-space:pre-wrap;word-break:break-word;background:#f7f6f9;padding:12px;border-radius:12px;font-size:11px}.mobile-nav{display:none}@media(max-width:540px){.mobile-nav{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;position:fixed;left:8px;right:8px;bottom:8px;z-index:20;padding:6px;background:rgba(255,255,255,.96);border:1px solid var(--line);border-radius:17px;box-shadow:0 8px 30px rgba(20,15,40,.12)}.mobile-nav button{min-height:42px;padding:8px 4px;font-size:12px;border:0;background:transparent}.mobile-nav button.primary{background:var(--accent);color:#fff}.mobile-nav+*{padding-bottom:0}}
@media(max-width:540px){main{padding:8px 9px 80px}.hero{padding:20px 17px;border-radius:21px}.hero h1{font-size:28px}.hero-main{grid-template-columns:1fr}.hero-main button{width:100%}.choice-grid{grid-template-columns:1fr}.card{padding:15px;border-radius:17px}.summary{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><div><div class="brand">MINI IP <span style="font-size:11px;background:#dff5f1;color:#087c59;padding:4px 7px;border-radius:99px;vertical-align:middle">NEW</span></div><div class="muted">Твоя студия персонажа</div></div><div id="server" class="pill">ПОДКЛЮЧЕНИЕ…</div></div>

<section class="hero"><span class="eyebrow">MINI IP</span><h1>Создадим персонажа, которого хочется узнать.</h1><p>Сначала создаём основу и внешний образ. Потом Mini IP помогает искать его сильную сторону через реальные эксперименты.</p><div class="hero-main"><div class="muted" style="color:#c9c7cf">Начнём с самого важного — кто он и как выглядит.</div><button class="primary" onclick="showCharacter()">Создать персонажа →</button></div></section>

<section class="card" id="character-card"><div class="step">1 · Персонаж</div><h2>Кто это?</h2><p class="muted">Дай имя и несколько слов о характере. Остальное можно развивать постепенно.</p><div class="label">Имя</div><input id="name" value="Леся" placeholder="Например, Леся"><div class="label">Что в нём важно</div><textarea id="dna" placeholder="Характер, стиль, поведение, внешность…"></textarea><div class="actions"><button class="primary" onclick="saveCharacter()">Сохранить персонажа</button><button onclick="randomDNA()">✨ Дать случайную ДНК</button></div><div id="character-status" class="status">Персонаж ещё не сохранён.</div></section>

<section class="card" id="photo-card"><div class="step">2 · Внешность</div><h2>Добавь фотографию</h2><p class="muted">Здесь загружается фото-референс персонажа. Оно сохраняется вместе с его карточкой.</p><div class="photo-box"><strong>📷 Фото персонажа</strong><span class="muted">JPG, PNG или WebP · до 10 МБ</span><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" onchange="previewPhoto()"></div><div id="photo-preview" class="photo-preview" style="display:none"><img id="photo-img"></div><div class="actions"><button class="primary" onclick="uploadPhoto()">Сохранить фото</button></div><div id="photo-status" class="status">Фото ещё не добавлено.</div></section>

<section class="card" id="growth-card"><div class="step">3 · Путь персонажа</div><h2>Куда его развивать?</h2><p class="muted">Можно выбрать то, чего хочется сейчас. Или ничего не выбирать — Mini IP сам попробует разные варианты.</p>
<div id="growth-options" class="choice-grid">
<button onclick="chooseGrowth('Популярность')">🌟 Популярность<small>Чтобы его узнавали</small></button>
<button onclick="chooseGrowth('Характер и юмор')">😏 Характер и юмор<small>Чтобы у него был свой голос</small></button>
<button onclick="chooseGrowth('Истории и личность')">📖 Истории<small>Собственная жизнь и сюжет</small></button>
<button onclick="chooseGrowth('Визуальный IP')">🎨 Визуальный образ<small>Узнаваемость и стиль</small></button>
<button onclick="chooseGrowth('Социальные сети')">📱 Соцсети<small>Общение и аудитория</small></button>
<button onclick="chooseGrowth('Коммерческий IP')">💼 Коммерческий путь<small>Бренды и лицензирование</small></button>
<button onclick="chooseGrowth('Медиа')">🎬 Медиа<small>Шоу, фотоистории, контент</small></button>
<button onclick="chooseGrowth('Эксперимент')">🧪 Не знаю<small>Пусть Mini IP найдёт путь</small></button></div>
<div class="label">Хочешь — напиши своими словами</div><textarea id="growth-brief" placeholder="Например: хочу, чтобы Леся стала узнаваемой и со временем превратилась в настоящий IP."></textarea>
<div class="actions"><button class="primary" onclick="saveGrowth()">Сохранить мой замысел</button><button onclick="startDiscovery()">🔮 Пусть Mini IP найдёт путь</button></div><div id="growth-status" class="status">Выбери направление или доверь поиск Mini IP.</div></section>

<section class="card"><div class="step">4 · Первый результат</div><h2>Давай сделаем первый контент</h2><p class="muted">Можно начать с готовой идеи и потом менять её.</p><textarea id="brief">Кафе в Москве. Леся с капучино смотрит прямо в камеру. Ложкой размешивает кофе по часовой стрелке и говорит: «Тоже в эту сторону».</textarea><div class="sticky"><button class="primary" onclick="produce()">Создать первый контент →</button></div><div id="result" class="status">Готово к запуску.</div></section>

<section class="card"><div class="step">Текущий персонаж</div><h2 id="profileName">Леся</h2><div class="summary"><div><span>Материалов</span><b id="count">0</b></div><div><span>Последний результат</span><b id="signal">—</b></div><div><span>Развитие</span><b id="evolution">Готово</b></div><div><span>Владелец</span><b id="owner">—</b></div></div></section>

<section class="card"><div class="step">Библиотека</div><h2>Результаты</h2><div id="gallery" class="gallery"><span class="muted">Здесь появится первый контент.</span></div></section>
<section class="card"><details><summary>Техническое состояние</summary><pre id="debug">—</pre></details></section>
</main><nav class="mobile-nav"><button onclick="showCharacter()">Персонаж</button><button onclick="document.getElementById('photo-card')?.scrollIntoView({behavior:'smooth'})">Фото</button><button onclick="showGrowth()">Путь</button><button class="primary" onclick="produce()">Контент</button></nav></body><script>
let owner=localStorage.mini_ip_owner||'',character=localStorage.mini_ip_character||'',token=localStorage.mini_ip_token||'';
let growth=JSON.parse(localStorage.mini_ip_growth||'null')||{direction:'',directions:[],brief:'',mode:'',discovery:false,jobs:[]};
if(!Array.isArray(growth.directions))growth.directions=growth.direction?[growth.direction]:[];
function syncGrowthDirections(){growth.direction=growth.directions.join(' + ')}
function persistGrowth(){localStorage.mini_ip_growth=JSON.stringify(growth)}
function showGrowth(){document.getElementById('growth-card')?.scrollIntoView({behavior:'smooth',block:'start'})}
function showCharacter(){document.getElementById('character-card')?.scrollIntoView({behavior:'smooth',block:'start'})}
function chooseGrowth(direction){const i=growth.directions.indexOf(direction);if(i>=0)growth.directions.splice(i,1);else growth.directions.push(direction);syncGrowthDirections();document.querySelectorAll('#growth-options button').forEach(b=>b.classList.toggle('selected',growth.directions.some(d=>b.textContent.includes(d))));$('growth-status').textContent=growth.directions.length?'Выбрано: '+growth.directions.join(', ')+'. Можно добавить свой замысел или сразу начать поиск.':'Пока направление не выбрано.';persistGrowth()}
async function saveGrowth(){try{await ensureCharacter();growth.brief=$('growth-brief').value.trim();growth.mode='owner-guided';if(!growth.direction)growth.direction='Свободное развитие';persistGrowth();await api('/characters/'+character+'/preferences',{method:'POST',body:JSON.stringify({owner_id:owner,patch:{growth_plan:{direction:growth.direction,brief:growth.brief,mode:growth.mode}}})});$('growth-status').innerHTML='<span class="ok">✓ Замысел сохранён.</span> Mini IP будет использовать его как ориентир, но направление можно изменить в любой момент.'}catch(e){$('growth-status').textContent=e.message}}
async function startDiscovery(){try{await ensureCharacter();growth.discovery=true;growth.mode='discovery';growth.jobs=[];persistGrowth();$('growth-status').textContent='Mini IP запускает небольшую обкатку: проверяем несколько разных сторон персонажа…';const ideas=[['Повседневность','discovery_daily','Персонаж в простой узнаваемой жизненной ситуации'],['Юмор','discovery_humor','Короткая ироничная ситуация, раскрывающая характер'],['История','discovery_story','Небольшая эмоциональная история персонажа'],['Визуальный образ','discovery_visual','Сильная визуальная сцена для проверки узнаваемости'],['Общение','discovery_social','Ситуация, рассчитанная на реакцию аудитории'],['Неожиданность','discovery_surprise','Необычная ситуация, способная выделить персонажа']];for(const idea of ideas){const context=(growth.direction?'Ориентиры развития: '+growth.direction+'. ':'')+(growth.brief?'Замысел владельца: '+growth.brief+'. ':'');const brief=context+idea[2];const x=await api('/jobs',{method:'POST',body:JSON.stringify({owner_id:owner,character_id:character,platform:'local-test',brief,idea:{mechanic:idea[1],hook:idea[2],brief:brief}})});growth.jobs.push({id:x.job_id,label:idea[0],mechanic:idea[1]})}persistGrowth();$('growth-status').textContent='✓ Обкатка запущена. Mini IP проверяет 6 разных вариантов и будет использовать результаты для следующего решения.';pollDiscovery()}catch(e){$('growth-status').textContent=e.message}}
async function pollDiscovery(){if(!growth.jobs?.length)return;let done=0;for(const j of growth.jobs){try{const x=await api('/jobs/'+j.id);j.status=x.status;if(['SUCCEEDED','DEAD_LETTER','FAILED'].includes(x.status))done++}catch(e){}}persistGrowth();$('growth-status').textContent=done===growth.jobs.length?'✓ Обкатка завершена. Mini IP собрал первый опыт персонажа.':'Идёт обкатка персонажа: '+done+'/'+growth.jobs.length+' экспериментов завершено.';if(done<growth.jobs.length)setTimeout(pollDiscovery,1800);else refresh()}
const $=id=>document.getElementById(id);
function headers(){let h={'Content-Type':'application/json','X-Owner-ID':owner};if(token)h.Authorization='Bearer '+token;return h}
async function api(p,o={}){o.headers=Object.assign(headers(),o.headers||{});let r=await fetch(p,o),x=await r.json().catch(()=>({}));if(r.status===401)throw Error('Требуется ключ доступа');if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));return x}
async function auth(){try{let c=await fetch('/config').then(r=>r.json());if(c.auth_required&&!token){token=prompt('Введите токен доступа Mini IP:')||'';localStorage.mini_ip_token=token}if(!owner){let x=await api('/owners',{method:'POST',body:'{}'});owner=x.owner_id;localStorage.mini_ip_owner=owner}await refresh()}catch(e){$('server').textContent='ОШИБКА ДОСТУПА';$('server').className='pill bad';$('debug').textContent=e.message}}
async function ensureCharacter(){if(character)return character;let x=await api('/characters',{method:'POST',body:JSON.stringify({owner_id:owner,name:'Леся',card:{description:'Взрослый вымышленный персонаж; строгий медно-рыжий боб с прямой чёлкой; выразительные зелёно-серые глаза; прямой взгляд; московская визуальная среда; естественная асимметрия 10–15%.',user_controls:{dna_notes:'',voice:{source:'synthetic'}}}})});character=x.character_id;localStorage.mini_ip_character=character;return character}
async function saveCharacter(){try{await ensureCharacter();let x=await api('/characters/'+character+'/preferences',{method:'POST',body:JSON.stringify({owner_id:owner,patch:{dna_notes:$('dna').value,voice:{source:'synthetic',description:'Голосовая ДНК персонажа'}}})});$('character-status').innerHTML='<span class="ok">✓ Персонаж сохранён.</span>'; $('result').textContent='Персонаж готов. Можно добавить фото или сразу создавать контент.';await refresh()}catch(e){$('result').textContent=e.message}}
function previewPhoto(){const f=$('photo').files[0];if(!f)return;$('photo-img').src=URL.createObjectURL(f);$('photo-preview').style.display='block';$('photo-status').textContent='Фотография выбрана. Нажмите «Сохранить фотографию».'}
function clearPhoto(){$('photo').value='';$('photo-preview').style.display='none';$('photo-status').textContent='Фотография ещё не добавлена.'}
async function uploadPhoto(){try{await ensureCharacter();const f=$('photo').files[0];if(!f)throw Error('Сначала выберите фотографию');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Поддерживаются JPG, PNG и WebP');if(f.size>10*1024*1024)throw Error('Фотография должна быть не больше 10 МБ');let h={'Content-Type':f.type,'X-Owner-ID':owner,'X-Filename':f.name};if(token)h.Authorization='Bearer '+token;let r=await fetch('/characters/'+character+'/reference',{method:'POST',headers:h,body:f}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));$('photo-status').textContent='✓ Фотография сохранена и подключена к персонажу';$('photo-status').className='status ok';await refresh()}catch(e){$('photo-status').textContent=e.message;$('photo-status').className='bad'}}

async function randomDNA(){try{await ensureCharacter();let x=await api('/characters/'+character+'/randomize-dna',{method:'POST',body:JSON.stringify({owner_id:owner})});let d=(x.card||{}).user_controls?.random_dna||{};$('dna').value=Object.entries(d).map(([k,v])=>k+': '+v).join(', ')}catch(e){$('result').textContent=e.message}}
async function produce(){try{await saveCharacter();let base=$('brief').value.trim(),context=(growth.direction?'Направление развития: '+growth.direction+'. ':'')+(growth.brief?'Замысел владельца: '+growth.brief+'. ':'');let fullBrief=context+base;let x=await api('/jobs',{method:'POST',body:JSON.stringify({owner_id:owner,character_id:character,platform:'local-test',brief:fullBrief,idea:{mechanic:growth.discovery?'guided_discovery':'user_brief',hook:base,brief:fullBrief,direction:growth.direction||'',owner_intent:growth.brief||''}})});$('result').textContent='В ОЧЕРЕДИ · '+x.job_id;let id=x.job_id,n=0,t=setInterval(async()=>{try{let j=await api('/jobs/'+id);$('result').textContent=({QUEUED:'В ОЧЕРЕДИ',RUNNING:'В РАБОТЕ',SUCCEEDED:'ВЫПОЛНЕНО',DEAD_LETTER:'ОСТАНОВЛЕНО',FAILED:'ОШИБКА'}[j.status]||j.status)+' · '+(j.error||'Цикл выполняется');if(['SUCCEEDED','DEAD_LETTER','FAILED'].includes(j.status)||++n>120){clearInterval(t);refresh()}}catch(e){clearInterval(t);$('result').textContent=e.message}},1500)}catch(e){$('result').textContent=e.message}}
async function refresh(){try{let h=await fetch('/health').then(r=>r.json()),rr=await fetch('/ready'),rd=await rr.json();$('server').textContent=rr.ok?'В СЕТИ':'НЕ ГОТОВ';$('server').className='pill '+(rr.ok?'ok':'bad');if(!owner)return;let s=await api('/status/'+owner),c=(s.characters_detail||[]).find(x=>x.character_id===character)||(s.characters_detail||[])[0];if(c&&!character){character=c.character_id;localStorage.mini_ip_character=character}if(c){$('profileName').textContent=c.name;$('name').value=c.name;$('dna').value=(c.card?.user_controls?.dna_notes)||$('dna').value;const gp=c.card?.user_controls?.growth_plan;if(gp&&!growth.direction){growth.direction=gp.direction||'';growth.directions=gp.direction?String(gp.direction).split(' + ').filter(Boolean):[];growth.brief=gp.brief||'';growth.mode=gp.mode||'';document.querySelectorAll('#growth-options button').forEach(b=>b.classList.toggle('selected',growth.directions.some(d=>b.textContent.includes(d))));persistGrowth()}}let gr=s.growth?.[character];if(gr?.recommendation){$('growth-status').innerHTML='<b>Mini IP видит перспективное направление:</b> '+gr.recommendation+'<br><span class="muted">Это пока гипотеза. Уверенность '+Math.round((gr.confidence||0)*100)+'%. Её нужно проверить следующими экспериментами.</span>'}else if(gr?.message&&growth.discovery){$('growth-status').textContent=gr.message} let jobs=s.jobs_detail||[],active=jobs.find(j=>['QUEUED','RUNNING'].includes(j.status));$('owner').textContent=owner.slice(0,18)+'…';$('count').textContent=(s.artifacts_detail||[]).length;$('signal').textContent=({QUEUED:'В ОЧЕРЕДИ',RUNNING:'В РАБОТЕ',SUCCEEDED:'ВЫПОЛНЕНО',DEAD_LETTER:'ОСТАНОВЛЕНО',FAILED:'ОШИБКА'}[jobs[0]?.status]||jobs[0]?.status||'—');$('evolution').textContent=active?'Идёт обучение':'Готова к следующему циклу';const ref=(s.artifacts_detail||[]).find(a=>a.character_id===character&&a.variant==='reference');if(ref){$('photo-status').textContent='✓ Фотография персонажа сохранена';$('photo-status').className='status ok';} $('debug').textContent=JSON.stringify({health:h,ready:rd,owner,character,jobs:jobs.slice(0,8)},null,2);await gallery(s.artifacts_detail||[])}catch(e){$('debug').textContent=e.message}}
async function gallery(items){if(!items.length){$('gallery').innerHTML='<span class="muted">Пока нет готовых артефактов.</span>';return}$('gallery').innerHTML='';for(const a of items.slice().reverse()){let d=document.createElement('div');d.className='tile';let img=document.createElement('img');try{let r=await fetch('/artifacts/'+a.artifact_id,{headers:headers()});img.src=URL.createObjectURL(await r.blob())}catch(e){}d.appendChild(img);let m=document.createElement('div');m.textContent=({APPROVED:'ГОТОВО',PENDING:'ОЖИДАЕТ',FAILED:'ОШИБКА'}[a.status]||a.status||'')+' · '+(a.variant==='master'?'основной вариант':(a.variant||'материал'));d.appendChild(m);$('gallery').appendChild(d)}}
if(growth.direction){$('growth-status').textContent='Текущее направление: '+growth.direction+(growth.discovery?' · обкатка включена':'');if($('growth-brief'))$('growth-brief').value=growth.brief||''} auth();setInterval(refresh,10000);
</script></html>