from __future__ import annotations
import json
HTML = r"""<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GLOBAL FACTORY 2</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#07080c;color:#f5f7fb;font:15px/1.5 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-size:24px;font-weight:900}.muted{color:#8e98aa}.grid{display:grid;grid-template-columns:1.4fr .8fr;gap:16px;margin-top:18px}.card{background:#10131b;border:1px solid #292f3d;border-radius:18px;padding:18px}.hero{min-height:250px;display:flex;flex-direction:column;justify-content:center}.big{font-size:44px;line-height:1;font-weight:900;margin:10px 0}.pill{padding:7px 10px;border-radius:99px;border:1px solid #303746}.ok{color:#72e6a7}.warn{color:#f2c75c}.bad{color:#ff7186}button{background:#171c26;border:1px solid #343b4b;color:#fff;padding:11px 14px;border-radius:11px;cursor:pointer}button.primary{background:linear-gradient(135deg,#6d3fd9,#a477ff);border:0;color:#08090c;font-weight:850}button.danger{color:#ff9aaa;border-color:#63303b}input,select{width:100%;background:#090c12;color:#fff;border:1px solid #303746;border-radius:10px;padding:11px;margin:6px 0}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.metric{background:#0b0e14;border:1px solid #252b38;border-radius:12px;padding:13px}.metric b{display:block;font-size:23px}.row{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid #202633}.hidden{display:none}.login{max-width:430px;margin:12vh auto}.notice{padding:10px;border:1px solid #3a3440;border-radius:10px;margin-top:10px}.toast{position:fixed;right:18px;bottom:18px;background:#171c25;border:1px solid #343b4b;padding:12px;border-radius:11px;display:none}@media(max-width:760px){.grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.big{font-size:36px}}
</style></head><body><main id="login" class="login"><div class="card"><div class="brand">GLOBAL FACTORY 2</div><p class="muted">AI IP Growth Factory · Owner Control</p><input id="user" placeholder="Логин" autocomplete="username"><input id="pass" placeholder="Пароль" type="password" autocomplete="current-password"><div class="actions"><button class="primary" onclick="register()">Создать Owner</button><button onclick="login()">Войти</button></div><div id="authmsg" class="notice muted">Первый вход создаёт локальную Owner identity. Социальные пароли сюда не вводятся.</div></div></main>
<main id="app" class="hidden"><div class="top"><div><div class="brand">GLOBAL FACTORY 2</div><div class="muted">Autonomous IP Growth Factory</div></div><div id="state" class="pill">—</div></div>
<section class="grid"><div class="card hero"><div class="muted">OWNER CONTROL</div><div class="big" id="hero">Готова</div><div class="muted">Сложность работает внутри. Тебе остаётся запустить фабрику и смотреть результат.</div><div class="actions"><button class="primary" onclick="start()">▶ ПУСК</button><button onclick="pause()">⏸ Пауза</button><button class="danger" onclick="stop()">🛑 STOP</button><button onclick="fund()">💰 Пополнить</button></div></div>
<div class="card"><h3>Growth Fund</h3><div class="big" id="balance">$0</div><div class="muted">Бюджет роста</div><hr><div class="row"><span>Режим</span><b id="mode">organic</b></div><div class="row"><span>Автономность</span><b id="auto">2</b></div><div class="row"><span>Safe Mode</span><b id="safe">OFF</b></div></div></section>
<div class="metrics"><div class="metric"><span class="muted">IP</span><b id="ips">0</b></div><div class="metric"><span class="muted">Контент</span><b id="content">0</b></div><div class="metric"><span class="muted">Публикации</span><b id="pubs">0</b></div><div class="metric"><span class="muted">Платформы</span><b id="platforms">0</b></div></div>
<section class="grid"><div class="card"><h3>IP Portfolio</h3><div id="characters"></div></div><div class="card"><h3>Social / Compliance</h3><p class="muted">Пароли соцсетей не хранятся. Подключение — только OAuth/API.</p><div id="social"></div><div class="actions"><select id="platform"><option>youtube</option><option>telegram</option><option>vk</option><option>instagram</option><option>tiktok</option><option>x</option></select><button onclick="connect()">Подключить</button></div></div></section>
<section class="card" style="margin-top:16px"><h3>Последние события</h3><pre id="events" class="muted">—</pre></section></main><div id="toast" class="toast"></div>
<script>
let token=localStorage.gf2_token||'';
const $=id=>document.getElementById(id);
function msg(x){$('authmsg').textContent=x}
async function api(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(token)opt.headers.Authorization='Bearer '+token;let r=await fetch(path,opt),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.message||x.error||('HTTP '+r.status));return x}
async function register(){try{let x=await api('/factory2/api/register',{method:'POST',body:JSON.stringify({username:$('user').value,password:$('pass').value})});token=x.token;localStorage.gf2_token=token;show();await refresh()}catch(e){msg(e.message)}}
async function login(){try{let x=await api('/factory2/api/login',{method:'POST',body:JSON.stringify({username:$('user').value,password:$('pass').value})});token=x.token;localStorage.gf2_token=token;show();await refresh()}catch(e){msg(e.message)}}
function show(){$('login').classList.add('hidden');$('app').classList.remove('hidden')}
function toast(x){$('toast').textContent=x;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
async function act(p,b){try{let x=await api('/factory2/api/'+p,{method:'POST',body:JSON.stringify(b||{})});toast(x.message||'Готово');await refresh()}catch(e){toast(e.message)}}
function start(){act('start')}function pause(){act('pause')}function stop(){act('stop')}
async function fund(){let a=prompt('Сколько добавить в Growth Fund?');if(a)act('fund',{amount:Number(a)})}
async function connect(){act('platform',{platform:$('platform').value})}
async function refresh(){try{let x=await api('/factory2/api/dashboard');$('state').textContent=x.running?'● RUNNING':'○ PAUSED';$('state').className='pill '+(x.running?'ok':'');$('hero').textContent=x.running?'Фабрика работает':'Готова к запуску';$('balance').textContent='$'+Number(x.fund.balance).toFixed(2);$('mode').textContent=x.growth_mode;$('auto').textContent=x.autonomy;$('safe').textContent=x.safe_mode?'ON':'OFF';$('ips').textContent=x.characters.length;$('content').textContent=x.content_count;$('pubs').textContent=x.published_count;$('platforms').textContent=x.platforms.length;$('characters').innerHTML=x.characters.map(c=>'<div class="row"><span>'+c.name+'</span><b>'+c.state+'</b></div>').join('')||'<span class="muted">Пока нет IP</span>';$('social').innerHTML=x.platforms.map(p=>'<div class="row"><span>'+p.platform+'</span><b class="'+(p.legal_class==='GREEN'?'ok':'warn')+'">'+p.status+' · '+p.legal_class+'</b></div>').join('')||'<span class="muted">Пока ничего не подключено</span>';$('events').textContent=x.events.map(e=>new Date(e.created_at*1000).toLocaleString()+'  '+e.kind+'  '+JSON.stringify(e.detail)).join('\n')||'Событий пока нет'}catch(e){if(e.message==='unauthorized'){localStorage.removeItem('gf2_token');location.reload()}}}
if(token)show();if(token)refresh();setInterval(()=>{if(token)refresh()},8000)
</script></body></html>"""
def send_html(handler):
    b=HTML.encode("utf-8"); handler.send_response(200); handler.send_header("Content-Type","text/html; charset=utf-8"); handler.send_header("Cache-Control","no-store"); handler.send_header("Content-Length",str(len(b))); handler.end_headers(); handler.wfile.write(b)
